/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.controladorAtivosFinanceiros;

import controller.controladorAtivosFinanceiros.ControladorAtivosFinaceirosController;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import model.controladorAtivosFinanceiros.Acionista;

/**
 *
 * @author vapstor
 */
public class TelaLogin extends javax.swing.JFrame {
    
    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    TelaLogin(String cpf) {
        this.inputCPF.setText(cpf);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        inputCPF = new JFormattedTextField(setMascara("###.###.###-##"));
        labelCPF = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        inputPassword = new javax.swing.JPasswordField();
        panelActions = new javax.swing.JPanel();
        novoUsuarioBtn = new javax.swing.JButton();
        buscarUsuarioBtn = new javax.swing.JButton();
        quitBtn = new javax.swing.JButton();
        loginBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder("Bem vindo!"));

        labelCPF.setText("CPF:");

        titulo.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        titulo.setText("Login");

        labelPassword.setText("Senha:");

        novoUsuarioBtn.setText("Novo usuário");
        novoUsuarioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoUsuarioBtnActionPerformed(evt);
            }
        });

        buscarUsuarioBtn.setText("Buscar usuário");
        buscarUsuarioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarUsuarioBtnActionPerformed(evt);
            }
        });

        quitBtn.setText("Sair");
        quitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitBtnActionPerformed(evt);
            }
        });

        loginBtn.setText("Entrar");
        loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelActionsLayout = new javax.swing.GroupLayout(panelActions);
        panelActions.setLayout(panelActionsLayout);
        panelActionsLayout.setHorizontalGroup(
            panelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActionsLayout.createSequentialGroup()
                .addComponent(novoUsuarioBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buscarUsuarioBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(quitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panelActionsLayout.setVerticalGroup(
            panelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelActionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(panelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(novoUsuarioBtn)
                    .addComponent(buscarUsuarioBtn)
                    .addComponent(quitBtn))
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelPrincipalLayout.createSequentialGroup()
                                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelPassword)
                                    .addComponent(labelCPF))
                                .addGap(18, 18, 18)
                                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputPassword)
                                    .addComponent(inputCPF)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelPrincipalLayout.createSequentialGroup()
                                .addComponent(titulo)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                        .addComponent(panelActions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addGap(28, 28, 28)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCPF)
                    .addComponent(inputCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPassword)
                    .addComponent(inputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelActions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        ControladorAtivosFinaceirosController caf = new ControladorAtivosFinaceirosController();
        String pass;
        Acionista acionista = null;
        try {
            char[] password = inputPassword.getPassword();
            pass = String.valueOf(password);
            String valueCPF = inputCPF.getText();
            boolean isLogged = caf.autenticaUser(valueCPF, pass);
            if(!isLogged) {
                 JOptionPane.showMessageDialog(this, "Senha ou Usuário Incorreto" 
                        + "\n"
                        + "Favor revisar as Informações", "Dados Incorretos", JOptionPane.ERROR_MESSAGE);
            } else {
                acionista = caf.findByCPF(valueCPF);
                this.setVisible(false);
                abreTelaInicialLogado(acionista);
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, 
                                    "Nao foi possivel salvar contato!"+ "\n" + 
                                    e.getLocalizedMessage()
                            );
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, 
				"Formato inválido!" + "\n" + 
				e.getLocalizedMessage()
		);
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void novoUsuarioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoUsuarioBtnActionPerformed
        this.setVisible(false);
        TelaAdicionarAcionista();
    }//GEN-LAST:event_novoUsuarioBtnActionPerformed

    private void buscarUsuarioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarUsuarioBtnActionPerformed
        String valueCPF = (JOptionPane.showInputDialog(this, 
                "Digite o CPF Para Consulta: ", 
                "Consulta por CPF", 
                JOptionPane.PLAIN_MESSAGE, null, null, 
                "Digite no Formato xxx.xxx.xxx-xx")).toString();
        try {
            if(valueCPF.length() != 14) {
                JOptionPane.showMessageDialog(this, "Confira os dados! (xxx.xxx.xxx-xx)","Erro de Formatação", JOptionPane.ERROR_MESSAGE);
            } else {
                ControladorAtivosFinaceirosController caf = new ControladorAtivosFinaceirosController();
                Acionista acionista = caf.findByCPF(valueCPF);
                this.setVisible(false);
                abreTelaPerfilAcionista(acionista);
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, 
                                    "Nao foi possivel encontrar o contato!"+ "\n" + 
                                    e.getLocalizedMessage()
                            );
        }
    }//GEN-LAST:event_buscarUsuarioBtnActionPerformed

    private void quitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitBtnActionPerformed
        int dialogButton = JOptionPane.showConfirmDialog(this, "Você realmente deseja sair?", "Sair", JOptionPane.YES_NO_OPTION);
        if(dialogButton == JOptionPane.YES_OPTION) {
            System.exit(1);
        }
    }//GEN-LAST:event_quitBtnActionPerformed
    
    private MaskFormatter setMascara(String mascara){
        MaskFormatter mask = null;
        try{
            mask = new MaskFormatter(mascara);
        }catch(java.text.ParseException ex){}
        return mask;
    }
    
    
    private void TelaAdicionarAcionista() {
        TelaAdicionarAcionista adicionarAcionista = new TelaAdicionarAcionista();
        adicionarAcionista.setVisible(true);
    }
    
    
    private void abreTelaInicialLogado(Acionista acionistaLogado) {
        TelaInicialLogado telaLogado = new TelaInicialLogado();
        telaLogado.recebeAcionista(acionistaLogado);
        telaLogado.setVisible(true);
    }

    private void abreTelaPerfilAcionista(Acionista acionista) {
        TelaPerfilAcionista perfilAcionista = new TelaPerfilAcionista();
        perfilAcionista.recebeAcionista(acionista);
        perfilAcionista.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarUsuarioBtn;
    private javax.swing.JFormattedTextField inputCPF;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JLabel labelCPF;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JButton loginBtn;
    private javax.swing.JButton novoUsuarioBtn;
    private javax.swing.JPanel panelActions;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JButton quitBtn;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables

    

    
}
