
package auth.view;
import auth.view.TelaLogin;
import acionistas.controller.AcionistasController;
import acoes.dao.CarteiraDAO;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import javax.swing.JFormattedTextField;
import acoes.model.Carteira;
/**
 *
 * @author vapstor
 */
public class TelaAdicionarAcionista extends javax.swing.JFrame {

    public TelaAdicionarAcionista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelInputs = new javax.swing.JPanel();
        inputNome = new javax.swing.JTextField();
        inputCarteira = new javax.swing.JTextField();
        labelCPF = new javax.swing.JLabel();
        inputCPF = new JFormattedTextField(setMascara("###.###.###-##"));
        labelCarteira = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        inputPassword = new javax.swing.JPasswordField();
        addUserBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inputCarteira.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputCarteiraKeyReleased(evt);
            }
        });

        labelCPF.setText("CPF:");

        labelCarteira.setText("Nº Carteira:");

        labelNome.setText("Nome:");

        titulo.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        titulo.setText("Adicionar Acionista");

        labelPassword.setText("Senha");

        javax.swing.GroupLayout panelInputsLayout = new javax.swing.GroupLayout(panelInputs);
        panelInputs.setLayout(panelInputsLayout);
        panelInputsLayout.setHorizontalGroup(
            panelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInputsLayout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .addComponent(titulo)
                .addGap(111, 111, 111))
            .addGroup(panelInputsLayout.createSequentialGroup()
                .addGroup(panelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNome)
                    .addComponent(labelCPF)
                    .addComponent(labelCarteira)
                    .addComponent(labelPassword))
                .addGap(30, 30, 30)
                .addGroup(panelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputCarteira, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inputNome)
                    .addComponent(inputCPF)
                    .addComponent(inputPassword)))
        );
        panelInputsLayout.setVerticalGroup(
            panelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInputsLayout.createSequentialGroup()
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(panelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCPF)
                    .addComponent(inputCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(panelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(panelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCarteira)
                    .addComponent(inputCarteira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(panelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPassword)
                    .addComponent(inputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        addUserBtn.setText("Adicionar Usuário");
        addUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickAddUser(evt);
            }
        });

        cancelBtn.setText("Cancelar");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelInputs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelPrincipalLayout.createSequentialGroup()
                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelInputs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addUserBtn)
                    .addComponent(cancelBtn))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onClickAddUser(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onClickAddUser
        AcionistasController ac = new AcionistasController();
        CarteiraDAO cd = new CarteiraDAO();
        
        String pass;
        char[] password = inputPassword.getPassword();
        pass = String.valueOf(password);
        
        String valueCPF = inputCPF.getText();
        String valueNome = inputNome.getText();
        int valueIdCarteira = Integer.parseInt(inputCarteira.getText());
        
        boolean valido = ac.validaCampos(this, valueCPF, valueNome, valueIdCarteira, pass);
        
        if(valido) {
            //tenta salvar o Acionista
            try {
                ac.addAcionista(this, valueCPF, valueNome, valueIdCarteira, pass);
                ac.addCarteira(this, valueIdCarteira);
                this.setVisible(false);   
                abreTelaLoginPosCadastro(valueCPF);
            } catch (SQLException e ) {
                 System.out.println("Erro SQL" + e);
                //Testa se o CPF Já Existe na Base e Lança Exceção
                if(e.toString().equalsIgnoreCase(
                        "com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '"+ valueCPF + "' for key 'PRIMARY'"))
                    {
                        JOptionPane.showMessageDialog(this, "O CPF " + valueCPF + " já foi cadastrado" + "\n" 
                        + "Favor revisar as Informações", "CPF Já Salvo", JOptionPane.ERROR_MESSAGE);
                    }

                //Teste Carteira Cadastrados
                else if(e.toString().equalsIgnoreCase(
                        "com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '"+ valueIdCarteira + "' for key 'PRIMARY'"))
                        {
                            JOptionPane.showMessageDialog(this, "A Carteira " + valueCPF + " já foi cadastrada" + "\n" 
                            + "Favor revisar as Informações", "Carteira Já Salva", JOptionPane.ERROR_MESSAGE);
                        }

                //Teste CPF && Carteira Cadastrados
                else if(e.toString().equalsIgnoreCase(
                        "com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '"+ valueCPF+"-"+valueIdCarteira + "' for key 'PRIMARY'"))
                {
                    JOptionPane.showMessageDialog(this, "O CPF " + valueCPF + "\n"+ 
                            "E a Carteira " + valueIdCarteira + "\n" +
                            "já foram cadastrados" + "\n" 
                            + "Favor revisar as Informações", "CPF e Carteira Já Salvos", JOptionPane.ERROR_MESSAGE);
                }
                
                else {
                    JOptionPane.showMessageDialog(this, "Erro no BD!" + "\n" + e);
                }

            } catch (ParseException ex) {
                Logger.getLogger(TelaAdicionarAcionista.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Nao foi possível salvar contato!" + "\n" + ex.getLocalizedMessage());
            }
                catch (Exception error){
                    JOptionPane.showMessageDialog(this, "Erro!" + "\n" + error);
                };
        }
    }//GEN-LAST:event_onClickAddUser

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.setVisible(false);
        abreTelaLogin();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void inputCarteiraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputCarteiraKeyReleased
        try {
            int number = Integer.parseInt(this.inputCarteira.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Somente Números Permitidos");
            this.inputCarteira.setText("");
        }
    }//GEN-LAST:event_inputCarteiraKeyReleased
    
    private void clearFields() {
        inputCPF.setText("");
        inputNome.setText("");
        inputCarteira.setText("");
        inputPassword.setText("");
    }
    
     private MaskFormatter setMascara(String mascara){
        MaskFormatter mask = null;
        try{
            mask = new MaskFormatter(mascara);                      
        }catch(java.text.ParseException ex){}
        return mask;
    }
    
    private void abreTelaLogin() {
        TelaLogin tl = new TelaLogin();
        tl.setVisible(true);
    }
    
    private void abreTelaLoginPosCadastro(String cpf) {
        TelaLogin tl = new TelaLogin(cpf);
        tl.setVisible(true);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUserBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JFormattedTextField inputCPF;
    private javax.swing.JTextField inputCarteira;
    private javax.swing.JTextField inputNome;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JLabel labelCPF;
    private javax.swing.JLabel labelCarteira;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JPanel panelInputs;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables

    
}
